from app.schemas.blueprint import APIEndpoint, APIOutput, DatabaseOutput, RequirementOutput


def design_api(requirements: RequirementOutput, database: DatabaseOutput) -> APIOutput:
    endpoints = [
        APIEndpoint(
            method="POST",
            path="/api/projects",
            description="Create a planning project from a natural-language idea.",
            request_schema={"idea": "string"},
            response_schema={"project_id": "string", "status": "string"},
            authentication_required=True,
        ),
        APIEndpoint(
            method="POST",
            path="/api/projects/{project_id}/workflow/run",
            description="Run the supervised blueprint generation workflow.",
            request_schema={"project_id": "string"},
            response_schema={"blueprint": "EngineeringBlueprint"},
            authentication_required=True,
        ),
        APIEndpoint(
            method="GET",
            path="/api/projects/{project_id}",
            description="Fetch project metadata and latest workflow status.",
            response_schema={"project": "ProjectSummary"},
            authentication_required=True,
        ),
        APIEndpoint(
            method="GET",
            path="/api/projects/{project_id}/artifacts",
            description="Fetch structured artifacts generated by all agents.",
            response_schema={"artifacts": "AgentOutput[]"},
            authentication_required=True,
        ),
    ]

    if any("track" in item.lower() for item in requirements.functional_requirements):
        endpoints.append(
            APIEndpoint(
                method="GET",
                path="/api/projects/{project_id}/workflow/status",
                description="Track the current workflow or order/request status represented by the blueprint.",
                response_schema={"stage": "string", "status": "string", "completed_stages": "string[]"},
                authentication_required=True,
            )
        )

    return APIOutput(
        endpoints=endpoints,
        authentication="JWT bearer authentication with role-based access checks.",
        error_cases=[
            "400 when the project idea is too short or malformed.",
            "401 when the user is not authenticated.",
            "403 when the user cannot access the project.",
            "404 when a project or artifact does not exist.",
            f"409 when stored artifacts conflict with {len(database.collections)} expected collections.",
        ],
    )
